#!/usr/bin/env bash
# Copyright (c) 2022-2023 MobileCoin Inc.

HOOKS_PATH=$(git config --get core.hooksPath)
PRE_COMMIT_HOOK_PATH="$HOOKS_PATH/pre-commit.d"

LINT_HOOK_PATH="$PRE_COMMIT_HOOK_PATH/lint"
DOT_ENV_HOOK_PATH="$PRE_COMMIT_HOOK_PATH/dotenv"

# Call lint hook
if [ -f "$LINT_HOOK_PATH" ]; then
    $LINT_HOOK_PATH
fi

# Call dotenv hook
if [ -f "$DOT_ENV_HOOK_PATH" ]; then
    $DOT_ENV_HOOK_PATH
fi