# Copyright (c) 2024 MobileCoin Inc.
name: release

on:
  push:
    tags:
    - '*.*.*'

permissions:
  contents: write

jobs:
  gh-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
